- name: Ensure the required directories exist and are assigned to app_user
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gunicorn_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    recurse: yes
  loop:
    - "{{ app_static_dir }}"
    - "{{ app_media_dir }}"
    - "{{ app_db_dir }}"
  become: true

- name: Populate systemd unit for running Django management commands on startup
  become: true
  ansible.builtin.template:
    src: django-init.service.j2
    dest: /etc/systemd/system/django-init.service
    mode: '0644'
  register: django_init_service

- name: Reload systemd to pick up new unit file
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: django_init_service.changed

- name: Enable and start the systemd service
  become: true
  ansible.builtin.systemd:
    name: "django-init.service"
    enabled: yes
    state: started
  when: django_init_service.changed
