- name: Ensure Python 3 is installed
  ansible.builtin.package:
    name: python3
    state: present

- name: Ensure python3-pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Ensure python3-apt is installed (for managing packages)
  ansible.builtin.package:
    name: python3-apt
    state: present

- name: Ensure Ansible uses the correct Python interpreter
  ansible.builtin.set_fact:
    ansible_python_interpreter: "/usr/bin/python3"
  when: ansible_distribution == "Ubuntu"
