---
- name: Restart Gunicorn
  ansible.builtin.systemd:
    name: gunicorn
    state: restarted
    enabled: yes
  become: true

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: true
