- name: Install Certbot
  apt:
    name: certbot
    state: present

- name: Obtain SSL certificates using Certbot
  become: true
  command: certbot --non-interactive --agree-tos --email "{{ cert_email }}" -d "{{ app_domain }}" --standalone certonly

- name: Set permissions for SSL certificates
  become: true
  file:
    path: "/etc/letsencrypt/live/{{ app_domain }}"
    owner: "{{ nginx_user }}"
    group: "{{ app_group }}"
    mode: '0644'  # for cert files
    recurse: yes

- name: Set correct permissions for the private key
  become: true
  file:
    path: "/etc/letsencrypt/live/{{ app_domain }}/privkey.pem"
    owner: root
    group: "{{ app_group }}"
    mode: '0600'

- name: Ensure Certbot auto-renewal cron job is present
  become: true
  cron:
    name: "Certbot auto-renewal"
    minute: "0"
    hour: "3"
    job: "certbot renew --quiet && systemctl reload nginx"
    state: present
