
- name: Ensure the directory for SSL certificates exists
  file:
    path: "/etc/letsencrypt/live/{{ app_domain }}"
    state: directory
    owner: root
    group: "{{ app_group }}"
    mode: '0755'
  become: true

- name: Set permissions for Nginx to read certificates
  file:
    path: "/etc/letsencrypt/live/{{ app_domain }}"
    owner: root
    group: "{{ app_group }}"
    mode: '0644'
    recurse: yes
  become: true
