- name: Add deadsnakes PPA (for newer Python versions)
  ansible.builtin.apt_repository:
    repo: "ppa:deadsnakes/ppa"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Python {{ app_python_version }}, virtualenv, and pip
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - python{{ app_python_version }}
    - python{{ app_python_version }}-venv
    - python3-pip
  become: true

- name: Create a virtual environment for the Django application using Python {{ app_python_version }}
  ansible.builtin.command:
    cmd: "/usr/bin/python{{ app_python_version }} -m venv {{ virtualenv_path }}"
  args:
    creates: "{{ virtualenv_path }}/activate"
  become: true
  become_user: "{{ app_user }}"
