- name: Build Python Package
  hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars/host_vars.yml"
  roles:
    - build_python_wheel

- name: Set up app's .env file
  hosts: web
  vars_files:
    - "{{ playbook_dir }}/../vars/host_vars.yml"
    - "{{ playbook_dir }}/../vars/encrypted_vars/app_env_vars.yml"
  tasks:
    - name: Set the path for the .env file
      set_fact:
        env_file_path: "{{ app_env_file_path }}"
    
    - name: Create and populate .env file
      include_role:
        name: create_env_file
      vars:
        env_vars: "{{ app_env_vars }}"

- name: Setup virtual environment and deploy
  hosts: web
  vars_files:
    - "{{ playbook_dir }}/../vars/host_vars.yml"
    - "{{ playbook_dir }}/../vars/encrypted_vars/host_vars.yml"
  roles:
    - setup_python_virtualenv
    - deploy_python_wheels
    - init_django_app
    - setup_gunicorn
    - setup_certificate_location
    - setup_nginx
    - setup_certbot
    - setup_nginx_ssl
