- name: Allow SSH traffic through UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
    state: enabled

- name: Check if UFW is enabled
  community.general.ufw:
    state: enabled
  register: ufw_status

- name: Debug UFW status
  debug:
    msg: "UFW was {{ 'enabled' if ufw_status.changed else 'not enabled' }}"
  
- name: Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS traffic on port 443
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
